import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardSidebar from "@/components/shared/DasboardSiderbar/DasboardSiderbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import TopNav from "@/components/shared/TopNav/TopNav";
import NotificationsList from "@/components/main-dashboard/Notifications/NotificationsList";
import Providers from "@/providers/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Abdelrhman Ali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider>
            <DashboardSidebar />

            <main className="flex-1 w-full p-4 overflow-y-auto">
              <TopNav />
              {children}
            </main>

            <NotificationsList />
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
